version: "3.7"
services:
  app:
    image: wanhuz/keepit:latest
    container_name: keepit-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    links:
      - db
    networks:
      - keepit



  nginx:
    image: nginx:alpine
    container_name: keepit-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./dev/docker-compose/nginx:/etc/nginx/conf.d/
    links:
      - app
    depends_on:
      - app
    networks:
      - keepit

networks:
  keepit:
    driver: bridge
