version: "3.7"
services:
  app:
    build:
      args:
        user: keepit
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: keepit-app
    container_name: keepit-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    links:
      - db
    networks:
      - keepit

  db:
    image: postgres:13.11-bullseye
    container_name: keepit-db
    restart: unless-stopped
    ports:
      - 3308:5432
    environment:
      POSTGRES_DB: keepit-db
      POSTGRES_PASSWORD: keepit-test
      POSTGRES_USER: keepit-user
    volumes:
      - "./sourcefiles/postgres:/home/wan/keepit/postgres/data"
    networks:
      - keepit

  nginx:
    image: nginx:alpine
    container_name: keepit-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./dev/docker-compose/nginx:/etc/nginx/conf.d/
    links:
      - app
    depends_on:
      - app
    networks:
      - keepit

networks:
  keepit:
    driver: bridge
