version: "3.7"
services:
  app:
    build:
      args:
        user: keepit
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: keepit-app
    container_name: keepit-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - keepit

  db:
    image: mysql:5.7
    container_name: keepit-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: keepit-db
      MYSQL_ROOT_PASSWORD: keepit-test
      MYSQL_PASSWORD: keepit-test
      MYSQL_USER: keepit-user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - keepit

  nginx:
    image: nginx:alpine
    container_name: keepit-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./dev/docker-compose/nginx:/etc/nginx/conf.d/
    links:
      - app
    depends_on:
      - app
    networks:
      - keepit

networks:
  keepit:
    driver: bridge